version: '3.5'
services:
  discovery:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    container_name: discovery-service

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - discovery
    container_name: service-gateway

  zipkin-service:
    build:
      context: ./zipkin-service
      dockerfile: Dockerfile
    ports:
      - "9411:9411"
    container_name: zipkin-service

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - discovery
    container_name: account-service

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - discovery
    container_name: customer-service