version: '3.8'

services:
  discovery:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    container_name: discovery-service
    networks:
      - microservices-network

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    container_name: service-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - discovery
    networks:
      - microservices-network

  zipkin-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9411:9411"
    container_name: zipkin-service
    networks:
      - microservices-network

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    container_name: account-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - discovery
    networks:
      - microservices-network

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    container_name: customer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - discovery
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
