server:
  port: ${PORT:9411}

spring:
  application:
    name: zipkin-service  
  cloud:
    discovery:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/  