apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: vasfidogan/customer-service:latest
        ports:
        - containerPort: 2222
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"  
        - name: EUREKA_SERVER
          value: "http://discovery-service:8761/eureka/"
